apiVersion: v1
kind: Service
metadata:
  name: pegb-ecommerce-frontend-svc-nodeport
  namespace: pegb-ecommerce
spec:
  type: NodePort
  selector:
    app: pegb-ecommerce-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30380
